[package]
name = "rideways"
version = "0.1.0"
authors = ["pal"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.32", features = ["ttf","image","gfx","mixer"] }
time = "0.1"
specs = "0.15"
specs-derive = "0.4"