[package]
name = "ecs_setup"
version = "0.1.0"
authors = ["Peter Allin <peter@peca.dk>"]
edition = "2018"

[dependencies]
ecs_components = { path = "../ecs_components" }
ecs_systems = { path = "../ecs_systems" }
shared_types = { path = "../shared_types" }
specs = "0.18"
