[package]
name = "geometry"
version = "0.1.0"
authors = ["Peter Allin <peter@peca.dk>"]
edition = "2018"


[dependencies]
sdl2 = { version = "0.35", features = ["ttf","image","gfx","mixer"] }
time = "0.3"
specs = "0.18"
specs-derive = "0.4"
rand = "0.8"
rand_core="0.6"
